server:
  port: 9090
spring:
  application:
    name: istad-final-employee-management-system-project
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: postgres
    password: chph9771
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  # validate file size
  servlet:
    multipart:
      max-request-size: 1MB
      max-file-size: 1MB
  file:
    upload-location: D:\\Istad-Spring\\istad-final-employee-management-system-project\\uploads
    preview-path: localhost:9090/uploads/
    download-path: localhost:9090/


